# Site settings
title: Hi, I'm Muskan Prakash.
description: Muskan Prakash's' professional portfolio site



# User settings
username: Muskan Prakash
user_title: Ms.
user_summary: Data Analyst with 2+ years of experience leveraging Python, SQL, and Power BI to extract insights, build dashboards, and reducing reporting time by 30% 
and boosting operational efficiency by 15%. Mastered in forecasting, predictive modeling, and streamlining reporting processes to improve business 
email:muskanprakash461@gmail.com
github_username:  3Muskan

exclude: ['package.json', 'src' , 'node_modules']
